### ISSUE TITLE
no commands show

### ISSUE THREAD

**Issue by StormCrasher783** [w36131/ScpEconomy#1]
the only command that shows is the setbalance and you need PlayerSensitiveDataAccess which is stupid. you should make it eco.SetBalance or something like that please

**Comment by w36131** [comment]
The command you are trying to execute is an admnistrative command, (ScpEconomy in RemoteAdmin is for administration) and there is another set of commands for economy (not for administration) type ".economy" in the client console (~) to see all economy related commands.
